apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-service
  template:
    metadata:
      labels:
        app: driver-service
    spec:
      containers:
        - name: driver-service
          image: github.com/trunglq04/goride/driver-service
          ports:
            - containerPort: 9092
              name: grpc
            - containerPort: 9091
              name: metrics
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          # Health Probe (check if pod ready)
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 15
            periodSeconds: 10
          env:
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_URI
            - name: JAEGER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JAEGER_ENDPOINT
---
apiVersion: v1
kind: Service
metadata:
  name: driver-service
spec:
  type: ClusterIP
  selector:
    app: driver-service
  ports:
    - port: 9092
      name: grpc
      targetPort: 9092
    - port: 9091
      name: metrics
      targetPort: 9091
